//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto4Final.verificaCliente {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="verificaCliente.WsClienteSoap")]
    public interface WsClienteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string registrarCliente(string nit, string nombre, string apellido, string telefono, string direccion, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> registrarClienteAsync(string nit, string nombre, string apellido, string telefono, string direccion, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ObtenerClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarExistenciaCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string verificarExistenciaCliente(string nit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarExistenciaCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> verificarExistenciaClienteAsync(string nit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsClienteSoapChannel : Proyecto4Final.verificaCliente.WsClienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsClienteSoapClient : System.ServiceModel.ClientBase<Proyecto4Final.verificaCliente.WsClienteSoap>, Proyecto4Final.verificaCliente.WsClienteSoap {
        
        public WsClienteSoapClient() {
        }
        
        public WsClienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsClienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsClienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsClienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string registrarCliente(string nit, string nombre, string apellido, string telefono, string direccion, string correo) {
            return base.Channel.registrarCliente(nit, nombre, apellido, telefono, direccion, correo);
        }
        
        public System.Threading.Tasks.Task<string> registrarClienteAsync(string nit, string nombre, string apellido, string telefono, string direccion, string correo) {
            return base.Channel.registrarClienteAsync(nit, nombre, apellido, telefono, direccion, correo);
        }
        
        public System.Data.DataTable ObtenerClientes() {
            return base.Channel.ObtenerClientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerClientesAsync() {
            return base.Channel.ObtenerClientesAsync();
        }
        
        public string verificarExistenciaCliente(string nit) {
            return base.Channel.verificarExistenciaCliente(nit);
        }
        
        public System.Threading.Tasks.Task<string> verificarExistenciaClienteAsync(string nit) {
            return base.Channel.verificarExistenciaClienteAsync(nit);
        }
    
    }
}
