//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto4Final.validarTarj {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://paquete/", ConfigurationName="validarTarj.validaTarjeta")]
    public interface validaTarjeta {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paquete/validaTarjeta/validaTCRequest", ReplyAction="http://paquete/validaTarjeta/validaTCResponse")]
        Proyecto4Final.validarTarj.validaTCResponse validaTC(Proyecto4Final.validarTarj.validaTCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://paquete/validaTarjeta/validaTCRequest", ReplyAction="http://paquete/validaTarjeta/validaTCResponse")]
        System.Threading.Tasks.Task<Proyecto4Final.validarTarj.validaTCResponse> validaTCAsync(Proyecto4Final.validarTarj.validaTCRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paquete/validaTarjeta/conexionRequest", ReplyAction="http://paquete/validaTarjeta/conexionResponse")]
        Proyecto4Final.validarTarj.conexionResponse conexion(Proyecto4Final.validarTarj.conexionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://paquete/validaTarjeta/conexionRequest", ReplyAction="http://paquete/validaTarjeta/conexionResponse")]
        System.Threading.Tasks.Task<Proyecto4Final.validarTarj.conexionResponse> conexionAsync(Proyecto4Final.validarTarj.conexionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaTCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaTC", Namespace="http://paquete/", Order=0)]
        public Proyecto4Final.validarTarj.validaTCRequestBody Body;
        
        public validaTCRequest() {
        }
        
        public validaTCRequest(Proyecto4Final.validarTarj.validaTCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaTCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int arg3;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int arg4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int arg5;
        
        public validaTCRequestBody() {
        }
        
        public validaTCRequestBody(string arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaTCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaTCResponse", Namespace="http://paquete/", Order=0)]
        public Proyecto4Final.validarTarj.validaTCResponseBody Body;
        
        public validaTCResponse() {
        }
        
        public validaTCResponse(Proyecto4Final.validarTarj.validaTCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaTCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public validaTCResponseBody() {
        }
        
        public validaTCResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class conexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="conexion", Namespace="http://paquete/", Order=0)]
        public Proyecto4Final.validarTarj.conexionRequestBody Body;
        
        public conexionRequest() {
        }
        
        public conexionRequest(Proyecto4Final.validarTarj.conexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class conexionRequestBody {
        
        public conexionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class conexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="conexionResponse", Namespace="http://paquete/", Order=0)]
        public Proyecto4Final.validarTarj.conexionResponseBody Body;
        
        public conexionResponse() {
        }
        
        public conexionResponse(Proyecto4Final.validarTarj.conexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class conexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public conexionResponseBody() {
        }
        
        public conexionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface validaTarjetaChannel : Proyecto4Final.validarTarj.validaTarjeta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class validaTarjetaClient : System.ServiceModel.ClientBase<Proyecto4Final.validarTarj.validaTarjeta>, Proyecto4Final.validarTarj.validaTarjeta {
        
        public validaTarjetaClient() {
        }
        
        public validaTarjetaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public validaTarjetaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validaTarjetaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public validaTarjetaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto4Final.validarTarj.validaTCResponse Proyecto4Final.validarTarj.validaTarjeta.validaTC(Proyecto4Final.validarTarj.validaTCRequest request) {
            return base.Channel.validaTC(request);
        }
        
        public string validaTC(string arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            Proyecto4Final.validarTarj.validaTCRequest inValue = new Proyecto4Final.validarTarj.validaTCRequest();
            inValue.Body = new Proyecto4Final.validarTarj.validaTCRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            Proyecto4Final.validarTarj.validaTCResponse retVal = ((Proyecto4Final.validarTarj.validaTarjeta)(this)).validaTC(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto4Final.validarTarj.validaTCResponse> Proyecto4Final.validarTarj.validaTarjeta.validaTCAsync(Proyecto4Final.validarTarj.validaTCRequest request) {
            return base.Channel.validaTCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto4Final.validarTarj.validaTCResponse> validaTCAsync(string arg0, string arg1, string arg2, int arg3, int arg4, int arg5) {
            Proyecto4Final.validarTarj.validaTCRequest inValue = new Proyecto4Final.validarTarj.validaTCRequest();
            inValue.Body = new Proyecto4Final.validarTarj.validaTCRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            inValue.Body.arg4 = arg4;
            inValue.Body.arg5 = arg5;
            return ((Proyecto4Final.validarTarj.validaTarjeta)(this)).validaTCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto4Final.validarTarj.conexionResponse Proyecto4Final.validarTarj.validaTarjeta.conexion(Proyecto4Final.validarTarj.conexionRequest request) {
            return base.Channel.conexion(request);
        }
        
        public string conexion() {
            Proyecto4Final.validarTarj.conexionRequest inValue = new Proyecto4Final.validarTarj.conexionRequest();
            inValue.Body = new Proyecto4Final.validarTarj.conexionRequestBody();
            Proyecto4Final.validarTarj.conexionResponse retVal = ((Proyecto4Final.validarTarj.validaTarjeta)(this)).conexion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto4Final.validarTarj.conexionResponse> Proyecto4Final.validarTarj.validaTarjeta.conexionAsync(Proyecto4Final.validarTarj.conexionRequest request) {
            return base.Channel.conexionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto4Final.validarTarj.conexionResponse> conexionAsync() {
            Proyecto4Final.validarTarj.conexionRequest inValue = new Proyecto4Final.validarTarj.conexionRequest();
            inValue.Body = new Proyecto4Final.validarTarj.conexionRequestBody();
            return ((Proyecto4Final.validarTarj.validaTarjeta)(this)).conexionAsync(inValue);
        }
    }
}
